# https://news.scorebooklive.com/texas/2023/04/21/vote-now-who-is-the-best-right-handed-pitcher-in-north-texas-high-school-softball
# you can download your the chrome driver here. set the absolute path to chrome_driver_path
# https://chromedriver.chromium.org/downloads
# https://googlechromelabs.github.io/chrome-for-testing/

js_source: https://secure.polldaddy.com/p/13562405.js
log_path: logs

# swap this out with whatever address the flask app is running off of.
flask_url: http://127.0.0.1:5000/

# item we want to win. this is the label of the radio button
poll_winner: Camas

# webpage that contains poll; to by used with dynamic js script
poll_page: https://highschool.athlonsports.com/national/2024/04/05/vote-for-best-high-school-mascot-in-america-sweet-16-camas-papermakers-vs-ashland-clockers

# https://docs.python.org/3/library/logging.html#logging-levels
log_level: 20
chrome_driver_path: /home/lozik/code/vote-pedro/driver/123/chromedriver

# Only set this to true if you want to refresh the dynamic-poll.js source. 
# Page source will be pulled from poll_page
set_dynamic_js: True
# Set this to True if you want to run the flask application from dynamic-poll.js
use_dynamic_js: True

# number of votes to be cast
votes_end: 100000
