# https://news.scorebooklive.com/texas/2023/04/21/vote-now-who-is-the-best-right-handed-pitcher-in-north-texas-high-school-softball
# you can download your the chrome driver here. set the absolute path to chrome_driver_path
# https://chromedriver.chromium.org/downloads
# https://googlechromelabs.github.io/chrome-for-testing/

js_source: https://secure.polldaddy.com/p/13562405.js
log_path: logs

# swap this out with whatever address the flask app is running off of.
flask_url: http://127.0.0.1:5000/

# item we want to win
poll_winner: Riley Harris

# webpage that contains poll
poll_page: https://highschool.athlonsports.com/texas/2024/04/01/vote-who-should-be-sblives-texas-high-school-athlete-of-the-week-4-1-2024

# https://docs.python.org/3/library/logging.html#logging-levels
log_level: 20
chrome_driver_path: /home/lozik/code/vote-pedro/driver/123/chromedriver

# Set to True if you want to update the contents of dynamic-poll.js
set_dynamic_js: True
# Set this to True if you want to run the flask application from dynamic-poll.js
use_dynamic_js: True

# number of votes to be cast
votes_end: 100000
